# Generated by Django 2.0.3 on 2018-04-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codChamado', models.CharField(max_length=20, verbose_name='codChamado')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('telefoneSolicitante', models.CharField(max_length=20, verbose_name='telefoneSolicitante')),
                ('departamentoSolicitante', models.CharField(max_length=50, verbose_name='departamentoSolicitante')),
                ('dataAbertura', models.CharField(max_length=20, verbose_name='dataAbertura')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em atendimento', 'Em atendimento'), ('concluído', 'Concluído'), ('cancelado', 'Cancelado')], default='Aberto', max_length=50, verbose_name='status')),
                ('visivel', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='Privado', max_length=50, verbose_name='visivel')),
                ('categoria', models.CharField(max_length=50, verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('chamados', models.ForeignKey(blank=True, null=True, on_delete='chamado', to='chamado.Chamado')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='funionariosAtendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete='funcionarioAtendimento', to='chamado.Funcionario'),
        ),
    ]
