# Generated by Django 2.0.3 on 2018-04-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0002_auto_20180402_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(max_length=50, verbose_name='status'),
        ),
    ]
